### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by takaqiao** [Goldenrevolver/Stardew-Valley-Mods#8]
`{
  /*
		Don't change the names inside {{placeHolder}}, they will get replaced with values.
    You can change the position of the {{placeHolder}} where they need to be in the sentence.
  */
  "Yes": "是",
  "No": "否",
  "GotPetted": "得到爱抚: {{value}}",
  "GotWater": "得到饮水: {{value}}",
  "GotFood": "得到喂食: {{value}}",
  "Friendship": "友好值: {{value}}",
  "HorseWarning": "骑马时你不能这么做!",
  "AteEnough": "{{name}} 今天吃的够多了.",
  "AteFood": "{{name}} 吃下了你喂的 {{foodName}}.",
  "AteFoodLove": "他爱吃这个.", // this is added after the translation of AteFood, the "they" refers to the horse
  "AteFoodLike": "他喜欢吃这个.", // this is added after the translation of AteFood, the "they" refers to the horse
  "AteFoodDislike": "这是很普通的零食，他并没有很享受吃这个.", // this is added after the translation of AteFood, the "they" refers to the horse (this is used for things like salmon berries and black berries for balancing)
  "HasHeater": "有加热器: {{value}}",
  "DontFeedChocolate": "巧克力？你不会是认真的吧！？",
  "LactoseIntolerantPets": "大多数猫和狗对乳糖都不耐受.",
  "LactoseIntolerantHorses": "大多数成年马匹对乳糖都不耐受.",
  "HorseHerbivore": "马是真正的草食动物，它们不能吃肉.",
  "HorseNoBread": "马不应该吃面包等加工食品.",
  "HorseEatShouldnt": "你的马不应该吃这个.",
  "HorseEatHay": "你的马在马厩里有足够的干草.",
  "HorseEatFiber": "你的马有足够的草料可以到处吃.",
  "HorseEatCoffee": "马不应该饮用咖啡或任何种类的咖啡因.",
  "HorseEatCabbage": "马不应该吃卷心菜或卷心菜属类的任何蔬菜.",
  "HorseEatOnion": "马不应该吃洋葱或洋葱属类的任何蔬菜.",
  "HorseEatNightshade": "马不应该吃茄属植物，包括土豆、西红柿、辣椒或茄子.",
  "HorseEatHorseRadish": "尽管名字叫马萝卜，但对马来说是危险的，而普通的萝卜则不是.",
  "HorseEatDislike": "你的马不想吃这个."
}`
Sorry for post issue to do this :P just kinda lazy to clone and PR
pastbin:https://pastebin.com/rLwbGR2F

**Comment by Goldenrevolver** [comment]
Used pull request #6 instead because it was posted first, please reopen if you want to request some of your changes instead of theirs
